// ===============================
// AUTH
// ===============================

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";




// redux/type.js

// ==================== STAFF ====================

export const CREATE_STAFF_REQUEST = "CREATE_STAFF_REQUEST";
export const CREATE_STAFF_SUCCESS = "CREATE_STAFF_SUCCESS";
export const CREATE_STAFF_FAILURE = "CREATE_STAFF_FAILURE";

// ==================== STUDENT ====================

export const CREATE_STUDENT_REQUEST = "CREATE_STUDENT_REQUEST";
export const CREATE_STUDENT_SUCCESS = "CREATE_STUDENT_SUCCESS";
export const CREATE_STUDENT_FAILURE = "CREATE_STUDENT_FAILURE";

// ==================== STUDENT ATTENDANCE ====================

export const MARK_STUDENT_ATTENDANCE_REQUEST =
  "MARK_STUDENT_ATTENDANCE_REQUEST";

export const MARK_STUDENT_ATTENDANCE_SUCCESS =
  "MARK_STUDENT_ATTENDANCE_SUCCESS";

export const MARK_STUDENT_ATTENDANCE_FAILURE =
  "MARK_STUDENT_ATTENDANCE_FAILURE";

// ==================== STAFF ATTENDANCE ====================

export const MARK_STAFF_ATTENDANCE_REQUEST =
  "MARK_STAFF_ATTENDANCE_REQUEST";

export const MARK_STAFF_ATTENDANCE_SUCCESS =
  "MARK_STAFF_ATTENDANCE_SUCCESS";

export const MARK_STAFF_ATTENDANCE_FAILURE =
  "MARK_STAFF_ATTENDANCE_FAILURE";







  export const GET_STUDENTS_REQUEST = "GET_STUDENTS_REQUEST";
export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS";
export const GET_STUDENTS_FAILURE = "GET_STUDENTS_FAILURE";

export const GET_STUDENT_REQUEST = "GET_STUDENT_REQUEST";
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS";
export const GET_STUDENT_FAILURE = "GET_STUDENT_FAILURE";

export const GET_STAFF_REQUEST = "GET_STAFF_REQUEST";
export const GET_STAFF_SUCCESS = "GET_STAFF_SUCCESS";
export const GET_STAFF_FAILURE = "GET_STAFF_FAILURE";

export const GET_STAFF_BY_ID_REQUEST = "GET_STAFF_BY_ID_REQUEST";
export const GET_STAFF_BY_ID_SUCCESS = "GET_STAFF_BY_ID_SUCCESS";
export const GET_STAFF_BY_ID_FAILURE = "GET_STAFF_BY_ID_FAILURE";

export const GET_CLASSES_REQUEST = "GET_CLASSES_REQUEST";
export const GET_CLASSES_SUCCESS = "GET_CLASSES_SUCCESS";
export const GET_CLASSES_FAILURE = "GET_CLASSES_FAILURE";

export const GET_CLASS_TIMETABLE_REQUEST = "GET_CLASS_TIMETABLE_REQUEST";
export const GET_CLASS_TIMETABLE_SUCCESS = "GET_CLASS_TIMETABLE_SUCCESS";
export const GET_CLASS_TIMETABLE_FAILURE = "GET_CLASS_TIMETABLE_FAILURE";

export const GET_FEES_REQUEST = "GET_FEES_REQUEST";
export const GET_FEES_SUCCESS = "GET_FEES_SUCCESS";
export const GET_FEES_FAILURE = "GET_FEES_FAILURE";

export const GET_EXPENSES_REQUEST = "GET_EXPENSES_REQUEST";
export const GET_EXPENSES_SUCCESS = "GET_EXPENSES_SUCCESS";
export const GET_EXPENSES_FAILURE = "GET_EXPENSES_FAILURE";

export const GET_SALARIES_REQUEST = "GET_SALARIES_REQUEST";
export const GET_SALARIES_SUCCESS = "GET_SALARIES_SUCCESS";
export const GET_SALARIES_FAILURE = "GET_SALARIES_FAILURE";